### ISSUE TITLE
give_Eulerian_Lagrangian_Distance, distances are (-\infty,L/2]

### ISSUE THREAD

**Issue by mountaindust** [mountaindust/IB2d#1]
This function is located in IBM_Blackbox (MATLAB version), and in the Python port, is contained within please_Find_Larangian_Forces_On_Eulerian_grid.py.

Function description claims to find "distance between... x and... y, at specified pts... and makes sure the distances are [0,L] accordingly."

In reality, the function only returns the distance between x and y if 0 <= dist(x,y) <= L/2. If dist(x,y) > L/2, the function will return L - dist(x,y), including negative numbers if dist(x,y) > L. Since this behavior seems counter intuitive and contrary to the stated behavior, it should be examined closely and either the behavior fixed or the documentation fixed.

/cc @nickabattista

**Comment by mountaindust** [comment]
After doing some more porting and examining the surrounding code, it seems to be that [0,L] is meant to be a periodic domain. In this case, the code is correct as long as the values for x and y are restricted to [0,L] (which they should be). I will add some documentation to the function explaining this.

**Comment by nickabattista** [comment]
Thanks Christopher! Sorry I haven't looked at the code, yet. You're killin
it! haha
